import Link from "next/link";
import { notFound } from "next/navigation";
import { getPage } from "@/features/reports/store";
import { ScoreGauge } from "@/components/ScoreGauge";

export default async function PageDetail({ params }: { params: Promise<{ id: string; pageId: string }> }) {
  const { id, pageId } = await params; const page = await getPage(id, pageId); if (!page) notFound();
  return <main className="detail-shell"><header><Link href={`/report/${id}`}>← Voltar ao relatório</Link><Link className="brand" href="/"><span className="brand-mark">L</span><span>Lumina</span></Link></header><section><div className="detail-title"><div><p>DETALHES DA PÁGINA</p><h1>{new URL(page.url).pathname || "/"}</h1><a href={page.url} target="_blank" rel="noreferrer">{page.url} ↗</a></div><ScoreGauge score={page.score} compact /></div><div className="detail-grid"><article><h2>Metadados</h2><dl><div><dt>Status HTTP</dt><dd>{page.statusCode || "Falha de acesso"}</dd></div><div><dt>Title</dt><dd>{page.title ?? "Não encontrado"}</dd></div><div><dt>Description</dt><dd>{page.description ?? "Não encontrada"}</dd></div><div><dt>Canonical</dt><dd>{page.canonical ?? "Não encontrado"}</dd></div><div><dt>Meta robots</dt><dd>{page.metaRobots ?? "Não definido"}</dd></div><div><dt>HTML lang</dt><dd>{page.lang ?? "Não definido"}</dd></div></dl></article><article><h2>Estrutura</h2><dl><div><dt>H1</dt><dd>{page.h1.join(" · ") || "Não encontrado"}</dd></div><div><dt>H2</dt><dd>{page.h2.slice(0,8).join(" · ") || "Não encontrado"}</dd></div><div><dt>HTML semântico</dt><dd>{page.semanticTags.join(" · ") || "Não encontrado"}</dd></div><div><dt>Palavras</dt><dd>{page.wordCount}</dd></div><div><dt>Links internos</dt><dd>{page.internalLinks.length}</dd></div><div><dt>Links externos</dt><dd>{page.externalLinks.length}</dd></div></dl></article></div><div className="detail-grid"><article><h2>Structured Data</h2>{page.schemaTypes.length ? <div className="chip-row">{page.schemaTypes.map((type) => <span key={type}>{type}</span>)}</div> : <p className="empty-copy">Nenhum JSON-LD válido foi encontrado nesta página.</p>}<pre>{page.schema.length ? JSON.stringify(page.schema, null, 2) : "Dados insuficientes"}</pre></article><article><h2>Problemas encontrados</h2>{page.issues.length ? <ul className="problem-list">{page.issues.map((issue) => <li key={issue}>× {issue}</li>)}</ul> : <p className="empty-copy">Nenhum problema básico encontrado.</p>}<h2>Entidades e autoria</h2><dl><div><dt>Autores</dt><dd>{page.authors.join(", ") || "Não identificados"}</dd></div><div><dt>Contatos</dt><dd>{[...page.emails, ...page.phones].join(" · ") || "Não identificados"}</dd></div><div><dt>Perfis sociais</dt><dd>{page.socialLinks.join(" · ") || "Não identificados"}</dd></div></dl></article></div><article className="content-preview"><h2>Conteúdo detectado</h2><p>{page.text || "Nenhum conteúdo textual foi extraído."}</p></article></section></main>;
}
