"use client";

import Link from "next/link";
import type { SiteReport } from "@/types/audit";
import { ScoreGauge } from "./ScoreGauge";
import { StatusBadge } from "./StatusBadge";

const impactOrder = { critical: 4, high: 3, medium: 2, low: 1 };
const schemaTypes = ["Organization", "LocalBusiness", "WebSite", "BreadcrumbList", "Article", "BlogPosting", "FAQPage", "Product", "Service", "Person"];

export function ReportView({ report }: { report: SiteReport }) {
  const issues = report.checks.filter((item) => item.status !== "passed").sort((a, b) => impactOrder[b.priority] - impactOrder[a.priority]);
  const date = new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(report.scannedAt));
  return (
    <div className="report-app">
      <aside className="sidebar print-hide">
        <Link className="brand" href="/"><span className="brand-mark">L</span><span>Lumina</span></Link>
        <nav><a href="#overview" className="active"><span>◫</span>Visão geral</a><a href="#crawlers"><span>⌁</span>AI Crawlers</a><a href="#schema"><span>{"{ }"}</span>Structured Data</a><a href="#interpretation"><span>✦</span>Como as IAs enxergam</a><a href="#pages"><span>▤</span>Páginas analisadas</a><a href="#recommendations"><span>↗</span>Recomendações</a><Link href="/history"><span>◷</span>Histórico</Link></nav>
        <div className="sidebar-note"><strong>O que este relatório mede</strong><p>Preparação técnica e editorial. Permissão de acesso não comprova visita ou citação por uma IA.</p></div>
      </aside>
      <main className="report-main">
        <header className="report-header print-hide"><div><Link href="/">← Nova análise</Link><strong>{report.domain}</strong><span>Última análise: {date}</span></div><button onClick={() => window.print()}>Gerar relatório <span>↗</span></button></header>
        <section className="report-content" id="overview">
          <div className="report-title"><div><p>RELATÓRIO DE VISIBILIDADE</p><h1>{report.domain}</h1><span>{report.pages.length} páginas analisadas em {(report.durationMs / 1000).toFixed(1)}s</span></div><div className="confidence-pill">Baseado em evidências do site</div></div>
          <article className="hero-score-card"><div><span>AI VISIBILITY SCORE</span><h2>{report.scoreLabel}</h2><p>O score soma regras mensuráveis de acesso, conteúdo, estrutura, entidades, autoridade e SEO técnico.</p><a href="#recommendations">Ver recomendações prioritárias →</a></div><ScoreGauge score={report.score} label={report.scoreLabel} /></article>
          <div className="category-grid">{report.categories.map((category) => { const percent = category.maxScore ? Math.round(category.score / category.maxScore * 100) : 0; return <article className="category-card" key={category.id}><div><span className="category-icon">{category.label.slice(0,2).toUpperCase()}</span><strong>{category.label}</strong></div><b>{percent}<small>/100</small></b><div className="meter"><i style={{ width: `${percent}%` }} /></div><small>{category.score} de {category.maxScore} pontos no score geral</small></article>; })}</div>

          <section className="report-section" id="crawlers"><div className="section-row"><div><p>ACESSO TÉCNICO</p><h2>AI Crawler Access</h2><span>Permitido indica capacidade de rastrear, não uma visita confirmada.</span></div><a href="#robots">Ver robots.txt →</a></div><div className="crawler-grid">{report.crawlerAccess.map((crawler) => <article className="crawler-card" key={crawler.userAgent}><div><span className="bot-icon">◎</span><div><strong>{crawler.name}</strong><small>{crawler.userAgent}</small></div></div><StatusBadge status={crawler.status} /><p>{crawler.explanation}</p><code>{crawler.rule}</code></article>)}</div></section>

          <section className="report-section"><div className="section-row"><div><p>PRIORIDADES</p><h2>Principais problemas</h2><span>Ordenados por impacto no score e na compreensão do site.</span></div><span className="issue-count">{issues.length} pontos a revisar</span></div><div className="issue-list">{issues.slice(0, 8).map((issue, index) => <article key={issue.id}><b>{String(index + 1).padStart(2,"0")}</b><div><strong>{issue.title}</strong><p>{issue.description}</p></div><span className={`impact ${issue.priority}`}>Impacto {issue.priority === "critical" ? "crítico" : issue.priority === "high" ? "alto" : issue.priority === "medium" ? "médio" : "baixo"}</span><em>{issue.score}/{issue.maxScore} pts</em></article>)}</div></section>

          <section className="report-section split-section" id="schema"><div><p className="kicker">ESTRUTURA EXPLÍCITA</p><h2>Structured Data</h2><div className="schema-list">{schemaTypes.map((type) => <div key={type}><span>{type}</span>{report.schemaCounts[type] ? <strong>{report.schemaCounts[type]} página(s)</strong> : <em>Não encontrado</em>}</div>)}</div></div><article className="entity-card"><span className="entity-label">ENTIDADE PRINCIPAL</span><h3>{report.entity.name ?? "Não identificada"}</h3><div className="confidence"><span><i style={{ width: `${report.entity.confidence}%` }} /></span><strong>{report.entity.confidence}% de confiança</strong></div><dl><div><dt>Descrição</dt><dd>{report.entity.description ?? "Dados insuficientes"}</dd></div><div><dt>Localização</dt><dd>{report.entity.location ?? "Não identificada"}</dd></div><div><dt>Contato</dt><dd>{report.entity.email ?? report.entity.phone ?? "Não identificado"}</dd></div><div><dt>Serviços</dt><dd>{report.entity.services.length ? report.entity.services.join(" · ") : "Não identificados"}</dd></div></dl><small>Evidências: {report.entity.evidence.join(", ") || "insuficientes"}.</small></article></section>

          <section className="report-section" id="interpretation"><div className="section-row"><div><p>LEITURA ESTRUTURADA</p><h2>Como uma IA interpreta seu site</h2><span>Representação obtida somente a partir do conteúdo encontrado.</span></div></div><div className="interpret-grid"><article><span>SITE</span><p>{report.pages[0]?.text.slice(0, 520) || "Nenhum conteúdo textual foi extraído."}</p></article><article><span>INTERPRETAÇÃO</span><dl><div><dt>Empresa</dt><dd>{report.interpretation.company}</dd></div><div><dt>Atividade</dt><dd>{report.interpretation.activity}</dd></div><div><dt>Público</dt><dd>{report.interpretation.audience}</dd></div><div><dt>Localização</dt><dd>{report.interpretation.location}</dd></div><div><dt>Diferenciais</dt><dd>{report.interpretation.differentials}</dd></div><div><dt>Fundador / autoria</dt><dd>{report.interpretation.founder}</dd></div></dl>{report.interpretation.missing.length > 0 && <div className="missing-box"><strong>Informações importantes não encontradas</strong>{report.interpretation.missing.map((item) => <span key={item}>× {item}</span>)}</div>}</article></div></section>

          <section className="report-section citation-section"><article><div><p>CITATION READINESS</p><h2>{report.citationScore}<small>/100</small></h2></div><ScoreGauge score={report.citationScore} compact /><span>Facilidade para extrair respostas com contexto, estrutura e sinais de verificação.</span></article><article><div><p>QUESTION COVERAGE</p><h2>{report.questionCoverageScore}<small>/100</small></h2></div><div className="question-list">{report.questions.map((item) => <div key={item.question}><span className={item.status}>{item.status === "answered" ? "✓" : item.status === "partial" ? "!" : "×"}</span><p><strong>{item.question}</strong><small>{item.status === "answered" ? "Respondida claramente" : item.status === "partial" ? "Parcialmente respondida" : "Não respondida"}</small></p></div>)}</div></article></section>

          <section className="report-section" id="pages"><div className="section-row"><div><p>COBERTURA DO SCAN</p><h2>Páginas analisadas</h2><span>Até 50 páginas internas, sem baixar imagens, fontes ou vídeos.</span></div><span className="issue-count">{report.pages.length} páginas</span></div><div className="table-wrap"><table><thead><tr><th>URL</th><th>Score</th><th>Status</th><th>Problemas</th><th /></tr></thead><tbody>{report.pages.map((page) => <tr key={page.id}><td><strong>{new URL(page.url).pathname || "/"}</strong><small>{page.title ?? "Sem title"}</small></td><td><b>{page.score}</b></td><td><span className={`page-status ${page.score >= 80 ? "good" : page.score >= 55 ? "warn" : "bad"}`}>{page.score >= 80 ? "Bom" : page.score >= 55 ? "Melhorar" : "Crítico"}</span></td><td>{page.issueCount}</td><td><Link href={`/report/${report.id}/page/${page.id}`} aria-label={`Ver detalhes de ${page.url}`}>→</Link></td></tr>)}</tbody></table></div></section>

          <section className="report-section" id="robots"><div className="section-row"><div><p>ARQUIVO TÉCNICO</p><h2>Robots.txt e sitemap</h2><span>{report.robotsUrl}</span></div><StatusBadge status={report.robotsText ? "passed" : "warning"} /></div><div className="robots-grid"><pre>{report.robotsText ?? "robots.txt não encontrado ou inacessível."}</pre><article><strong>Sitemap</strong><span>{report.sitemap.found ? "Encontrado" : "Não encontrado"}</span><dl><div><dt>URL</dt><dd>{report.sitemap.url ?? "Dados insuficientes"}</dd></div><div><dt>URLs declaradas</dt><dd>{report.sitemap.urlCount}</dd></div><div><dt>Amostras válidas</dt><dd>{report.sitemap.sampledOk}</dd></div></dl></article></div></section>

          <section className="report-section" id="recommendations"><div className="section-row"><div><p>PLANO DE AÇÃO</p><h2>Recomendações práticas</h2><span>Ordenadas por impacto × facilidade. Abra cada item para ver a correção.</span></div></div><div className="recommendation-list">{report.recommendations.map((item, index) => <details key={item.id} open={index === 0}><summary><b>{String(index + 1).padStart(2,"0")}</b><div><strong>{item.title}</strong><span>{item.problem}</span></div>{item.quickWin && <em>Quick Win</em>}<i>+</i></summary><div className="recommendation-body"><div><h4>Por que isso importa</h4><p>{item.why}</p><h4>Como corrigir</h4><p>{item.howTo}</p><h4>Páginas afetadas</h4><ul>{item.affectedPages.slice(0, 8).map((page) => <li key={page}>{page}</li>)}</ul></div><div><div className="rec-meta"><span>Impacto <strong>{item.impact}</strong></span><span>Dificuldade <strong>{item.difficulty}</strong></span></div><h4>Exemplo</h4><pre>{item.example}</pre></div></div></details>)}</div></section>
          <footer className="report-footer"><strong>Lumina</strong><span>Este relatório mede preparação para visibilidade em IA. Não confirma visitas, menções ou citações.</span><small>Gerado em {date}</small></footer>
        </section>
      </main>
    </div>
  );
}
